### ISSUE TITLE
Yara match attribut access

### ISSUE THREAD

**Issue by lbpierre** [matthw/icedid_stage1_unpack#2]
Hi,

Thank you for sharing your work, moreover, the article/write-up is really interesting and well written. 

I notice a small typo in the script line [255](https://github.com/matthw/icedid_stage1_unpack/blob/main/splcrypt_unpacker.py#L255) which could be fix by the following code:
_nb: I could not push the small fix I did in local, so here are the little tiny "patch"._

```python
for find in finds:
    # offset are relative to .text, rebase them
    off = self.pe.OPTIONAL_HEADER.ImageBase + section.VirtualAddress + find.strings[0][0]
    offsets.append(off)
```

Thanks again for sharing. :pray: 

For information, here is the version of the requirements is used:
```
angr==9.2.6
arc4==0.2.0
yara-python==4.2.0
pefile==2019.4.18
malduck==4.2.0
pyquicklz==1.4.1
```

**Comment by matthw** [comment]
Hello,

thank you very much for the feedback !
The root cause of the issue was that i had both ```yara``` and ```yara-python``` modules installed in my virtualenv...
```ìmport yara``` was pulling the first one, which has last been updated in 2014.

My fix is slightly different than the one you proposed as it needs to iterate over all matching offsets in order to try all potential rc4 code should there be multiple match like with sample ```db91742b64c866df2fc7445a4879ec5fc256319e234b1ac5a25589455b2d9e32```.

thank you for spotting it :)
